# ============================
# MOTION DETECTION CONFIG FILE
# ============================

video:
  source: "../data/video1.mp4"          
  fps: 600
         

alert:
  enabled: true

debug:
  show_contours: true

detector:
  enabled: true
  conf_threshold: 0.5
  weights_path: "yolov8n.pt"
  allowed_classes: {"person", "bicycle", "car", "dog", "cat", "bird", "cow", "horse"}
